name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_call:
    outputs:
      run_id:
        value: ${{ github.run_id }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: AWS-CDK.tgz
          path: .build/docset/AWS-CDK.tgz
