name: Docset

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_call:
    outputs:
      run_id:
        value: ${{ github.run_id }}
  workflow_dispatch: {}

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - run: make test/unit

  build:
    if: github.event_name != 'push'
    name: Build
    runs-on: ubuntu-22.04
    needs: unit-test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: AWS-CDK.tgz
          path: .build/latest/AWS-CDK.tgz

  acceptance-test:
    name: Acceptance Test
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - uses: actions/download-artifact@v3
        with:
          name: AWS-CDK.tgz
      - env:
          ACCTEST_TGZ: ./AWS-CDK.tgz
        run: make test/acc
